<?php

return [
    'sutunlar' => [
        // Kimlik & Bölge
        ['key' => 'IL',            'label' => 'İL',             'group' => 'Kimlik'],
        ['key' => 'BOLGE_ADI',     'label' => 'Bölge',          'group' => 'Kimlik'],
        ['key' => 'BASLIK',        'label' => 'Başlık',         'group' => 'Kimlik'],
        ['key' => 'SR',            'label' => 'SR',             'group' => 'Kimlik'],
        ['key' => 'FATURA NO',     'label' => 'Fatura No',      'group' => 'Fatura'],
        ['key' => 'FT',            'label' => 'FT',             'group' => 'Fatura'],
        ['key' => 'Tesisat',       'label' => 'Tesisat',        'group' => 'Fatura'],
        ['key' => 'A D R E S',     'label' => 'Adres',          'group' => 'Abone'],
        ['key' => 'MYIL',          'label' => 'M.Yıl',          'group' => 'Tarih'],
        ['key' => 'MUTA NO',       'label' => 'Muta No',        'group' => 'Abone'],
        // Okuma Tarihleri
        ['key' => 'İLK OKUMA',     'label' => 'İlk Okuma',     'group' => 'Tarih'],
        ['key' => 'OKUMA',         'label' => 'Okuma',          'group' => 'Tarih'],
        ['key' => 'TAHAKKUK',      'label' => 'Tahakkuk',       'group' => 'Tarih'],
        ['key' => 'İPTAL',         'label' => 'İptal',          'group' => 'Tarih'],
        ['key' => 'IPTAL',         'label' => 'İptal 2',        'group' => 'Tarih'],
        ['key' => 'TANZIM',        'label' => 'Tanzim',         'group' => 'Tarih'],
        ['key' => 'SON ÖDEME',     'label' => 'Son Ödeme',      'group' => 'Tarih'],
        // Abone Bilgileri
        ['key' => 'Ü N V A N',     'label' => 'Ünvan',          'group' => 'Abone'],
        ['key' => 'TRF',           'label' => 'TRF',            'group' => 'Abone'],
        ['key' => 'BLD',           'label' => 'BLD',            'group' => 'Abone'],
        ['key' => 'CEKILEN_GUC',   'label' => 'Çekilen Güç',   'group' => 'Teknik'],
        ['key' => 'VEZNE',         'label' => 'Vezne',          'group' => 'Tahsilat'],
        ['key' => 'VEZNEDAR',      'label' => 'Veznedar',       'group' => 'Tahsilat'],
        ['key' => 'VEZNE_ADI',     'label' => 'Vezne Adı',      'group' => 'Tahsilat'],
        ['key' => 'KART_',         'label' => 'Kart',           'group' => 'Tahsilat'],
        ['key' => 'TAKSIT',        'label' => 'Taksit',         'group' => 'Tahsilat'],
        // Tüketim
        ['key' => 'AKTIF KWH',     'label' => 'Aktif kWh',      'group' => 'Tüketim'],
        ['key' => 'AKTIF_MIKTAR',  'label' => 'Aktif Miktar',   'group' => 'Tüketim'],
        ['key' => 'REAKTIF_MIKTAR','label' => 'Reaktif Miktar', 'group' => 'Tüketim'],
        ['key' => 'MUHT. ILAVE',   'label' => 'Muht. İlave',   'group' => 'Tüketim'],
        ['key' => 'MUHT. TENZIL',  'label' => 'Muht. Tenzil',  'group' => 'Tüketim'],
        ['key' => 'AKTİF TÜKETİM','label' => 'Aktif Tüketim', 'group' => 'Tüketim'],
        ['key' => 'REAKTİF TÜKETİM','label' => 'Reaktif Tük.','group' => 'Tüketim'],
        // Bedeller
        ['key' => 'GUC BEDELI',    'label' => 'Güç Bedeli',     'group' => 'Bedel'],
        ['key' => 'GUC ASIMI BEDELI','label'=>'Güç Aşımı',      'group' => 'Bedel'],
        ['key' => 'SAYAC_AYAR_BEDELI','label'=>'S.Ayar',        'group' => 'Bedel'],
        ['key' => 'SAYAC_BEDELI',  'label' => 'Sayaç',          'group' => 'Bedel'],
        ['key' => 'SAYAC_MONTAJ_BEDELI','label'=>'S.Montaj',    'group' => 'Bedel'],
        ['key' => 'ACMA_KAPAMA_BEDELI','label'=>'Açma/Kapama',  'group' => 'Bedel'],
        ['key' => 'EE_FONU',       'label' => 'EE Fonu',        'group' => 'Vergi'],
        ['key' => 'TRT_PAYI',      'label' => 'TRT Payı',       'group' => 'Vergi'],
        ['key' => 'BELEDİYE VERGİSİ','label'=>'Belediye Verg.','group' => 'Vergi'],
        ['key' => 'K.D.V.',        'label' => 'KDV',            'group' => 'Vergi'],
        ['key' => 'DEVIR_YUVARLAMA','label'=>'Dev.Yuvarlama',   'group' => 'Bedel'],
        ['key' => 'DEVIR_GECIKME', 'label' => 'Dev.Gecikme',    'group' => 'Bedel'],
        ['key' => 'FATURA_TUTAR',  'label' => 'Fatura Tutar',   'group' => 'Tutar'],
        ['key' => 'TOPLAM TUTAR',  'label' => 'Toplam Tutar',   'group' => 'Tutar'],
        // Kimlik Numaraları
        ['key' => 'UNIPED',        'label' => 'UNIPED',         'group' => 'Kimlik'],
        ['key' => 'VDKod',         'label' => 'VD Kod',         'group' => 'Kimlik'],
        ['key' => 'VergiNo',       'label' => 'Vergi No',       'group' => 'Kimlik'],
        ['key' => 'TC.KimlikNo',   'label' => 'TC Kimlik',      'group' => 'Kimlik'],
        ['key' => 'SÖZL. GÜCÜ',   'label' => 'Sözl. Gücü',    'group' => 'Teknik'],
        ['key' => 'HESAP_KODU',    'label' => 'Hesap Kodu',     'group' => 'Kimlik'],
        ['key' => 'Fn',            'label' => 'Fn',             'group' => 'Fatura'],
        ['key' => 'MAHSUP_ILAVE',  'label' => 'Mahsup İlave',  'group' => 'Bedel'],
        ['key' => 'MAHSUP_TENZIL', 'label' => 'Mahsup Tenzil', 'group' => 'Bedel'],
        ['key' => 'BLG',           'label' => 'BLG',            'group' => 'Kimlik'],
        ['key' => 'F_BOLGE_KODU',  'label' => 'F.Bölge Kodu',  'group' => 'Kimlik'],
        ['key' => 'OKUYUCU_KODU',  'label' => 'Okuyucu Kodu',  'group' => 'Kimlik'],
        ['key' => 'OkumaSaat',     'label' => 'Okuma Saat',     'group' => 'Tarih'],
        ['key' => 'F_F',           'label' => 'F_F',            'group' => 'Fatura'],
        ['key' => 'F_FATURA_NO',   'label' => 'F.Fatura No',   'group' => 'Fatura'],
        // Dağıtım & İletim Bedelleri
        ['key' => 'DAGITIM BEDELI','label' => 'Dağıtım',        'group' => 'Bedel'],
        ['key' => 'PSH_BEDELI',    'label' => 'PSH',            'group' => 'Bedel'],
        ['key' => 'ILETIM_BEDELI', 'label' => 'İletim',         'group' => 'Bedel'],
        ['key' => 'OKUMA_BEDELI',  'label' => 'Okuma',          'group' => 'Bedel'],
        ['key' => 'KAYIP_BEDELI',  'label' => 'Kayıp',          'group' => 'Bedel'],
        ['key' => 'DAGITIM_BEDELI_TENZIL','label'=>'Dag.Tenzil','group' => 'Bedel'],
        ['key' => 'SISKUL_BEDELI', 'label' => 'Siskul',         'group' => 'Bedel'],
        ['key' => 'BAGLANTI_DUR',  'label' => 'Bağlantı Dur.',  'group' => 'Teknik'],
        ['key' => 'OG_DUR',        'label' => 'OG Dur.',        'group' => 'Teknik'],
        ['key' => 'KURULU GÜÇ',   'label' => 'Kurulu Güç',     'group' => 'Teknik'],
        ['key' => 'SÖZLEŞME',      'label' => 'Sözleşme',       'group' => 'Kimlik'],
        ['key' => 'YUVARLAMA',     'label' => 'Yuvarlama',      'group' => 'Bedel'],
        // KC (Kaçak) Alanları
        ['key' => 'KC_AKTIF_TUKETIM','label'=>'KC Aktif Tük.', 'group' => 'Kaçak'],
        ['key' => 'KC_DAGITIM_BEDELI','label'=>'KC Dağıtım',   'group' => 'Kaçak'],
        ['key' => 'KC_PSH_BEDELI', 'label' => 'KC PSH',         'group' => 'Kaçak'],
        ['key' => 'KC_ILETIM_BEDELI','label'=>'KC İletim',      'group' => 'Kaçak'],
        ['key' => 'KC_KAYIP_BEDELI','label'=>'KC Kayıp',        'group' => 'Kaçak'],
        ['key' => 'KC_OKUMA_BEDELI','label'=>'KC Okuma',        'group' => 'Kaçak'],
        // Alt İşletme & Hesap
        ['key' => 'ALT_ISLETME_ADI','label'=>'Alt İşletme',    'group' => 'Kimlik'],
        ['key' => 'ABONE_GRUP_ADI','label' => 'Abone Grup',     'group' => 'Kimlik'],
        ['key' => 'HESAP_ADI',     'label' => 'Hesap Adı',      'group' => 'Kimlik'],
        // Birim Fiyatlar
        ['key' => 'GUC_BIRIM_FIYAT','label'=>'Güç B.F.',       'group' => 'Birim'],
        ['key' => 'GUC_ASIMI_BIRIM_FIYAT','label'=>'Güç Aşım B.F.','group'=>'Birim'],
        ['key' => 'DAGITIM_BIRIM_FIYAT','label'=>'Dag. B.F.',   'group' => 'Birim'],
        ['key' => 'PSH_BIRIM_FIYAT','label'=>'PSH B.F.',        'group' => 'Birim'],
        ['key' => 'ILETIM_BIRIM_FIYAT','label'=>'İletim B.F.', 'group' => 'Birim'],
        ['key' => 'OKUMA_BIRIM_FIYAT','label'=>'Okuma B.F.',    'group' => 'Birim'],
        ['key' => 'KAYIP_BIRIM_FIYAT','label'=>'Kayıp B.F.',    'group' => 'Birim'],
        ['key' => 'SISKUL_BIRIM_FIYAT','label'=>'Siskul B.F.', 'group' => 'Birim'],
        ['key' => 'KACAK_CEZA_BIRIM_FIYAT','label'=>'Kaçak Ceza B.F.','group'=>'Birim'],
        // Sayaç
        ['key' => 'SAYAC_NO',      'label' => 'Sayaç No',       'group' => 'Sayaç'],
        ['key' => 'MAR',           'label' => 'MAR',            'group' => 'Sayaç'],
        ['key' => 'EFKS_FATURA_ID','label' => 'EFKS Fatura ID', 'group' => 'Fatura'],
        ['key' => 'AKIBET',        'label' => 'Akıbet',         'group' => 'Fatura'],
        ['key' => 'KARNE',         'label' => 'Karne',          'group' => 'Teknik'],
        ['key' => 'KARNE_KULLANIM','label' => 'Karne Kull.',    'group' => 'Teknik'],
        ['key' => 'CARPAN',        'label' => 'Çarpan',         'group' => 'Sayaç'],
        // T1-T5 Endeksler
        ['key' => 'T1_ILK_ENDEKS','label' => 'T1 İlk Endeks', 'group' => 'Endeks'],
        ['key' => 'T1_SON_ENDEKS', 'label' => 'T1 Son Endeks', 'group' => 'Endeks'],
        ['key' => 'T1_FARK',       'label' => 'T1 Fark',       'group' => 'Endeks'],
        ['key' => 'T1_TK_KWH',    'label' => 'T1 TK kWh',     'group' => 'Endeks'],
        ['key' => 'T1_ILAVE_KWH', 'label' => 'T1 İlave kWh',  'group' => 'Endeks'],
        ['key' => 'T2_ILK_ENDEKS','label' => 'T2 İlk Endeks', 'group' => 'Endeks'],
        ['key' => 'T2_SON_ENDEKS', 'label' => 'T2 Son Endeks', 'group' => 'Endeks'],
        ['key' => 'T2_FARK',       'label' => 'T2 Fark',       'group' => 'Endeks'],
        ['key' => 'T2_TK_KWH',    'label' => 'T2 TK kWh',     'group' => 'Endeks'],
        ['key' => 'T2_ILAVE_KWH', 'label' => 'T2 İlave kWh',  'group' => 'Endeks'],
        ['key' => 'T3_ILK_ENDEKS','label' => 'T3 İlk Endeks', 'group' => 'Endeks'],
        ['key' => 'T3_SON_ENDEKS', 'label' => 'T3 Son Endeks', 'group' => 'Endeks'],
        ['key' => 'T3_FARK',       'label' => 'T3 Fark',       'group' => 'Endeks'],
        ['key' => 'T3_TK_KWH',    'label' => 'T3 TK kWh',     'group' => 'Endeks'],
        ['key' => 'T3_ILAVE_KWH', 'label' => 'T3 İlave kWh',  'group' => 'Endeks'],
        ['key' => 'T4_ILK_ENDEKS','label' => 'T4 İlk Endeks', 'group' => 'Endeks'],
        ['key' => 'T4_SON_ENDEKS', 'label' => 'T4 Son Endeks', 'group' => 'Endeks'],
        ['key' => 'T4_FARK',       'label' => 'T4 Fark',       'group' => 'Endeks'],
        ['key' => 'T4_TK_KWH',    'label' => 'T4 TK kWh',     'group' => 'Endeks'],
        ['key' => 'T4_ILAVE_KWH', 'label' => 'T4 İlave kWh',  'group' => 'Endeks'],
        ['key' => 'T5_ILK_ENDEKS','label' => 'T5 İlk Endeks', 'group' => 'Endeks'],
        ['key' => 'T5_SON_ENDEKS', 'label' => 'T5 Son Endeks', 'group' => 'Endeks'],
        ['key' => 'T5_FARK',       'label' => 'T5 Fark',       'group' => 'Endeks'],
        ['key' => 'T5_TK_KWH',    'label' => 'T5 TK kWh',     'group' => 'Endeks'],
        ['key' => 'T5_ILAVE_KWH', 'label' => 'T5 İlave kWh',  'group' => 'Endeks'],
    ],

    'grup_renkleri' => [
        'Kimlik'    => 'bg-slate-100 text-slate-600 dark:bg-slate-700/50 dark:text-slate-400',
        'Fatura'    => 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300',
        'Abone'     => 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300',
        'Tarih'     => 'bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300',
        'Tüketim'   => 'bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300',
        'Bedel'     => 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300',
        'Vergi'     => 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
        'Tutar'     => 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300',
        'Teknik'    => 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
        'Birim'     => 'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300',
        'Sayaç'     => 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-300',
        'Endeks'    => 'bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300',
        'Kaçak'     => 'bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300',
        'Tahsilat'  => 'bg-lime-100 text-lime-700 dark:bg-lime-900/40 dark:text-lime-300',
    ],
    
    'filtre_kutuphaneleri' => [
        'temel' => ['IL', 'BOLGE_ADI', 'FATURA NO', 'Tesisat', 'MYIL', 'MUTA NO', 'TAHAKKUK', 'SON ÖDEME', 'Ü N V A N', 'FATURA_TUTAR', 'TOPLAM TUTAR', 'AKTİF TÜKETİM'],
        'tuketim' => ['FATURA NO', 'Tesisat', 'AKTIF KWH', 'AKTIF_MIKTAR', 'REAKTIF_MIKTAR', 'AKTİF TÜKETİM', 'REAKTİF TÜKETİM'],
        'tutar' => ['FATURA NO', 'Tesisat', 'GUC BEDELI', 'GUC ASIMI BEDELI', 'EE_FONU', 'TRT_PAYI', 'BELEDİYE VERGİSİ', 'K.D.V.', 'FATURA_TUTAR', 'TOPLAM TUTAR'],
    ]
];
